[General]
version=3.5.0
currentConnection=
fetchCovers=true
storeCoversInMpdDir=false
showPlaylist=true
useSystemTray=true
mpris=true

[Connection]
host=localhost
port=6600
dir=/home/johnny/Music
allowLocalStreaming=true
applyReplayGain=true
autoUpdate=true
name=
partition=
passwd=
replayGain=
