# Configuración del Administrador de Inactividad (Hypridle)
# Ubicación destino original: ~/.config/hypr/hypridle.conf

general {
    lock_cmd = pidof hyprlock || hyprlock          # Comando dbus para bloquear sesión
    before_sleep_cmd = loginctl lock-session       # Bloquear pantalla antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on     # Evita tener que presionar teclas extra para encender pantalla
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

# 1. Atenuar la pantalla tras 2.5 minutos de inactividad
listener {
    timeout = 150                                  # 150 segundos = 2.5 minutos
    on-timeout = brightnessctl -s set 10           # Guarda brillo actual y lo baja al mínimo (10)
    on-resume = brightnessctl -r                   # Restaura el brillo guardado
}

# 2. Apagar retroiluminación del teclado tras 2.5 minutos de inactividad (opcional)
listener {
    timeout = 150                                  # 150 segundos
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 # Apaga teclado (si aplica)
    on-resume = brightnessctl -rd rgb:kbd_backlight        # Enciende teclado
}

# 3. Bloquear la pantalla automáticamente tras 3 minutos de inactividad
listener {
    timeout = 180                                  # 180 segundos = 3 minutos
    on-timeout = loginctl lock-session             # Dispara hyprlock a través de systemd/loginctl
}

# 4. Apagar la pantalla (DPMS off) tras 3.5 minutos de inactividad (30s después del bloqueo)
listener {
    timeout = 210                                  # 210 segundos = 3.5 minutos (30s después del bloqueo)
    on-timeout = hyprctl dispatch dpms off         # Apaga señal de video del monitor
    on-resume = hyprctl dispatch dpms on           # Vuelve a encender el monitor al mover mouse o presionar teclas
}

# 5. Suspender la computadora tras 15 minutos de inactividad
listener {
    timeout = 900                                  # 900 segundos = 15 minutos
    on-timeout = systemctl suspend                 # Suspende el sistema a RAM
}
