# ==========================================
# Kitty Terminal Configuration (Catppuccin Mocha + JetBrains Mono)
# Ubicación original destino: ~/.config/kitty/kitty.conf
# ==========================================

# Tipografía
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        9.0

# Ligaduras de código
disable_ligatures never

# Cursor
cursor                  #f5e0dc
cursor_text_color       #11111b
cursor_shape            beam
cursor_blink_interval   0.5

# Ventana y Espaciado
window_padding_width    11
background_opacity      0.92
hide_window_decorations yes
confirm_os_window_close 0

# Colores Catppuccin Mocha
background              #181825
foreground              #cdd6f4
selection_background    #585b70
selection_foreground    #cdd6f4

# Paleta ANSI (Catppuccin Mocha)
# black
color0 #45475a
color8 #585b70
# red
color1 #f38ba8
color9 #f38ba8
# green
color2  #a6e3a1
color10 #a6e3a1
# yellow
color3  #f9e2af
color11 #f9e2af
# blue
color4  #89b4fa
color12 #89b4fa
# magenta
color5  #f5c2e7
color13 #f5c2e7
# cyan
color6  #94e2d5
color14 #94e2d5
# white
color7  #bac2de
color15 #a6adc8
